language: node_js
node_js:
    - "0.10"

branches:
    only:
        - master
        - dev

install:
    - npm install grunt-cli
    - npm install

cache:
    directories:
        - node_modules

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - ./node_modules/.bin/grunt travis